apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: git-tea
  namespace: argocd
spec:
  project: default
  source:
    chart: gitea
    repoURL: https://dl.gitea.com/charts/
    targetRevision: 12.3.0
    helm:
      releaseName: git-tea
      parameters:
        - name: clusterDomain
          value: git.aws.lockirin.pp.ua
        - name: gitea.admin.email
          value: gitea@git.aws.lockirin.pp.ua
        - name: ingress.hosts[0].host
          value: git.aws.lockirin.pp.ua
        - name: persistence.storageClass
          value: gp3
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  syncPolicy:
        automated:
          prune: true
          selfHeal: true

# project: default
# source:
#   repoURL: https://dl.gitea.com/charts
#   targetRevision: 12.3.0
#   helm:
#     parameters:
#       - name: clusterDomain
#         value: git.aws.lockirin.pp.ua
#       - name: gitea.admin.email
#         value: gitea@git.aws.lockirin.pp.ua
#       - name: ingress.hosts[0].host
#         value: git.aws.lockirin.pp.ua
#       - name: persistence.storageClass
#         value: gp3
#   chart: gitea
# destination:
#   server: https://kubernetes.default.svc
#   namespace: gitea
# syncPolicy:
#   automated: {}
#   syncOptions:
#     - CreateNamespace=true