apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: git-tea
  namespace: argocd
spec:
  project: default
  source:
    chart: gitea
    repoURL: https://dl.gitea.com/charts/
    targetRevision: 12.3.0
    helm:
      releaseName: git-tea
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default